
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.site;

import java.util.logging.Logger;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-04T19:23:56.066+01:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "EchoService",
                      portName = "EchoWSPort",
                      targetNamespace = "http://www.site.org",
                      wsdlLocation = "file:ECHO/Echo.wsdl",
                      endpointInterface = "org.site.EchoWS")
                      
public class EchoWSPortImpl implements EchoWS {

    private static final Logger LOG = Logger.getLogger(EchoWSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.site.EchoWS#echoAsync(java.lang.String  arg0 )*
     */
    public Response<org.site.EchoResponse> echoAsync(java.lang.String arg0) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see org.site.EchoWS#echoAsync(java.lang.String  arg0 ,)AsyncHandler<org.site.EchoResponse>  asyncHandler )*
     */
    public Future<?> echoAsync(java.lang.String arg0,AsyncHandler<org.site.EchoResponse> asyncHandler) { 
       return null;
       /* not called */
    }

    /* (non-Javadoc)
     * @see org.site.EchoWS#echo(java.lang.String  arg0 )*
     */
    public java.lang.String echo(java.lang.String arg0) { 
        LOG.info("Executing operation echo");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
