package org.site;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-04T19:23:56.072+01:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.site.org", name = "EchoWS")
@XmlSeeAlso({ObjectFactory.class})
public interface EchoWS {

    @WebMethod(operationName = "echo")
    @RequestWrapper(localName = "echo", targetNamespace = "http://www.site.org", className = "org.site.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://www.site.org", className = "org.site.EchoResponse")
    public Response<org.site.EchoResponse> echoAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod(operationName = "echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://www.site.org", className = "org.site.EchoResponse")
    @RequestWrapper(localName = "echo", targetNamespace = "http://www.site.org", className = "org.site.Echo")
    public Future<?> echoAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<org.site.EchoResponse> asyncHandler
    );

    @WebMethod
    @Action(input = "http://www.site.org/EchoWS/echoRequest", output = "http://www.site.org/EchoWS/echoResponse")
    @RequestWrapper(localName = "echo", targetNamespace = "http://www.site.org", className = "org.site.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://www.site.org", className = "org.site.EchoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
