
package org.site;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-05-04T19:23:56.075+01:00
 * Generated source version: 3.0.4
 * 
 */
 
public class EchoWS_EchoWSPort_Server{

    protected EchoWS_EchoWSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new EchoWSPortImpl();
        String address = "http://localhost:8080/ws/echo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new EchoWS_EchoWSPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
